// <auto-generated />
using System;
using EcoMonitor.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoMonitor.DataAccess.Migrations
{
    [DbContext(typeof(EcoMonitorDbContext))]
    [Migration("20251014104031_EcoMontorDB")]
    partial class EcoMontorDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.Auth.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.BinPhotoBinTypeEntity", b =>
                {
                    b.Property<Guid>("BinPhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BinTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("BinPhotoId", "BinTypeId");

                    b.HasIndex("BinTypeId");

                    b.ToTable("BinPhotoBinType");
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.BinPhotoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("FillLevel")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsOutsideBin")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (Point,4326)");

                    b.Property<int>("TotalBins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid");

                    b.Property<string>("UrlFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UploadedById");

                    b.ToTable("BinPhotos");
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.BinTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.HasKey("Id");

                    b.ToTable("BinTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c8a0efc-5587-442e-b25f-b6af0f838b8c"),
                            Code = "GLASS",
                            Name = "Стекло"
                        },
                        new
                        {
                            Id = new Guid("07a43844-8379-4346-a03f-771e99e05c07"),
                            Code = "PAPER",
                            Name = "Бумага и картон"
                        },
                        new
                        {
                            Id = new Guid("a83dc4d0-e3dc-4869-afb0-0272a1f3f6c6"),
                            Code = "PLASTIC",
                            Name = "Пластик"
                        },
                        new
                        {
                            Id = new Guid("bf2a3907-fe53-4d2e-93e5-844ab19f603c"),
                            Code = "METAL",
                            Name = "Металл"
                        },
                        new
                        {
                            Id = new Guid("a2663621-9339-47aa-a993-61aef83f5ced"),
                            Code = "ORGANIC",
                            Name = "Органика и пищевые отходы"
                        },
                        new
                        {
                            Id = new Guid("08e8aaa4-1620-4605-bd5d-df80101e9020"),
                            Code = "UNIVERSAL",
                            Name = "Смешанные отходы"
                        });
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.Users.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PermissionEntity");
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastLogindAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("isLoginConfirmed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.Users.UserRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b6ae3fe-f942-4dbb-8466-e36cfac114ab"),
                            Description = "Full access",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("4232bc2d-290b-4c77-8930-cde9d3d8762c"),
                            Description = "Manage photos and view/edit users",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("4278dcbc-cfdb-42e9-97be-bcf6267e9d49"),
                            Description = "Normal user access",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("PermissionEntityUserRoleEntity", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PermissionEntityUserRoleEntity");
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.Auth.RefreshTokenEntity", b =>
                {
                    b.HasOne("EcoMonitor.DataAccess.Entities.Users.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.BinPhotoBinTypeEntity", b =>
                {
                    b.HasOne("EcoMonitor.DataAccess.Entities.BinPhotoEntity", "BinPhoto")
                        .WithMany("BinPhotoBinTypes")
                        .HasForeignKey("BinPhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoMonitor.DataAccess.Entities.BinTypeEntity", "BinType")
                        .WithMany("BinPhotoBinTypes")
                        .HasForeignKey("BinTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinPhoto");

                    b.Navigation("BinType");
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.BinPhotoEntity", b =>
                {
                    b.HasOne("EcoMonitor.DataAccess.Entities.Users.UserEntity", "UploadedBy")
                        .WithMany("BinPhoto")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.Users.UserEntity", b =>
                {
                    b.HasOne("EcoMonitor.DataAccess.Entities.Users.UserRoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PermissionEntityUserRoleEntity", b =>
                {
                    b.HasOne("EcoMonitor.DataAccess.Entities.Users.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoMonitor.DataAccess.Entities.Users.UserRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.BinPhotoEntity", b =>
                {
                    b.Navigation("BinPhotoBinTypes");
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.BinTypeEntity", b =>
                {
                    b.Navigation("BinPhotoBinTypes");
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.Users.UserEntity", b =>
                {
                    b.Navigation("BinPhoto");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("EcoMonitor.DataAccess.Entities.Users.UserRoleEntity", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
